// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto " hery-ciaputra/assignment-05-golang-backend/dto"
	mock "github.com/stretchr/testify/mock"

	models " hery-ciaputra/assignment-05-golang-backend/models"
)

// WalletService is an autogenerated mock type for the WalletService type
type WalletService struct {
	mock.Mock
}

// GetTransactions provides a mock function with given fields: id, transactionFilter
func (_m *WalletService) GetTransactions(id int, transactionFilter *models.Filter) ([]*dto.TransactionsRes, error) {
	ret := _m.Called(id, transactionFilter)

	var r0 []*dto.TransactionsRes
	if rf, ok := ret.Get(0).(func(int, *models.Filter) []*dto.TransactionsRes); ok {
		r0 = rf(id, transactionFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.TransactionsRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *models.Filter) error); ok {
		r1 = rf(id, transactionFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWallet provides a mock function with given fields: id
func (_m *WalletService) GetWallet(id int) (*dto.WalletRes, error) {
	ret := _m.Called(id)

	var r0 *dto.WalletRes
	if rf, ok := ret.Get(0).(func(int) *dto.WalletRes); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WalletRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUpWallet provides a mock function with given fields: id, req
func (_m *WalletService) TopUpWallet(id int, req *dto.TopUpReq) (*dto.TopUpRes, error) {
	ret := _m.Called(id, req)

	var r0 *dto.TopUpRes
	if rf, ok := ret.Get(0).(func(int, *dto.TopUpReq) *dto.TopUpRes); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TopUpRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *dto.TopUpReq) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferWallet provides a mock function with given fields: id, req
func (_m *WalletService) TransferWallet(id int, req *dto.TransferReq) (*dto.TransferRes, error) {
	ret := _m.Called(id, req)

	var r0 *dto.TransferRes
	if rf, ok := ret.Get(0).(func(int, *dto.TransferReq) *dto.TransferRes); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TransferRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *dto.TransferReq) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWalletService interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletService creates a new instance of WalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletService(t mockConstructorTestingTNewWalletService) *WalletService {
	mock := &WalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
